Uwaga! Kod poniżej to jedno z ćwiczeń DataCamp (edytowane via [Spyder](https://www.spyder-ide.org/)).

In [ ]:
import pandas as pd
homelessness = pd.DataFrame([['East South Central', 'Alabama', 2570, 864, 4887681],
                             ['Pacific', 'Alaska', 1434, 582, 735139],
                             ['Mountain', 'Arizona', 7259, 2606, 7025024],
                             ['West South Central', 'Arkansas', 2280, 432, 3009733],
                             ['Pacific', 'California', 109008, 20964, 39461588]],
                            columns=['region', 'state', 'individuals', 'family_members', 'state_pop'])

print(homelessness.head())
print(homelessness.info())
print(homelessness.shape)
print(homelessness.describe())

print(homelessness.columns)
print(homelessness.index)
print(homelessness.values)

print(homelessness.sort_values('region'))
print(homelessness.sort_values(['individuals', 'region'], ascending=[False, True]))

print(homelessness[['state', 'individuals']])
ind_lessthan = homelessness['individuals'] < 10000
famm_morethan = homelessness['family_members'] > 500
print(homelessness[ind_lessthan & famm_morethan])
print(homelessness[(homelessness['individuals']<10000) & (homelessness['family_members']>500)])

is_in_state = homelessness['state'].isin(['Alabama', 'Arizona'])
print(homelessness[is_in_state])

def pct30(column):
    return column.quantile(0.3)
def pct40(column):
    return column.quantile(0.4)
print(homelessness[['individuals', 'state_pop']].agg([pct30, pct40]))

sales = pd.DataFrame([[1, 'A', 1, pd.to_datetime('2010-02-05'), 24924.50, False, 5.728, 0.679, 8.106],
                      [1, 'A', 2, pd.to_datetime('2010-03-05'), 21827.90, False, 8.056, 0.693, 8.106],
                      [2, 'A', 1, pd.to_datetime('2010-04-02'), 57258.43, False, 16.817, 0.718, 7.808],
                      [2, 'A', 2, pd.to_datetime('2010-05-07'), 17413.94, False, 22.528, 0.749, 7.808],
                      [2, 'A', 2, pd.to_datetime('2010-06-04'), 17558.09, False, 27.050, 0.715, 7.808]],
                      columns=['store','type', 'department', 'date', 'weekly_sales', 'is_holiday', 'temperature_c', 'fuel_price_usd_per_l', 'unemployment'])

sales_A = sales[sales['type']=='A']['weekly_sales'].sum()
sales_all = sales.groupby(['type', 'is_holiday'])['weekly_sales'].sum()
print(sales_A)
print(sales_all)

import numpy as np
print(sales.groupby('type')[['unemployment', 'fuel_price_usd_per_l']].agg([min, max, np.mean, np.median]))

print(sales.pivot_table(values='weekly_sales', index='type', aggfunc=[min, max, np.mean, np.median], margins=True))

sales_ind = sales.set_index(['store', 'date'])
print(sales_ind)
print(sales_ind.sort_index(level=['date', 'store'], ascending=[False, False]))
rows_to_keep = [(1, '2010-02-05'), (1, '2010-03-05'), (2, '2010-04-02')]
print(sales_ind.loc[rows_to_keep])
print(sales_ind.iloc[1:5, 2:3])

#Boolean conditions slicing can ONLY use full dates:
sales_bool = sales[(sales['date'] >= '2010-01-01') & (sales['date'] <= '2010-05-30')]
print(sales_bool['date'])

#Indexes CAN use trimmed dates:
sales_ind = sales.set_index('date').sort_index()
print(sales_ind.loc['2010-02':'2010-05'])
#WARNING! Not specyfying explicitly dtype introduces some peculiarities. For example, impossibility of:
print(sales.iloc[3,3].month)
print(sales['date'].dt.year)

               region       state  individuals  family_members  state_pop
0  East South Central     Alabama         2570             864    4887681
1             Pacific      Alaska         1434             582     735139
2            Mountain     Arizona         7259            2606    7025024
3  West South Central    Arkansas         2280             432    3009733
4             Pacific  California       109008           20964   39461588
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   region          5 non-null      object
 1   state           5 non-null      object
 2   individuals     5 non-null      int64
 3   family_members  5 non-null      int64
 4   state_pop       5 non-null      int64
dtypes: int64(3), object(2)
memory usage: 328.0+ bytes
None
(5, 5)
         individuals  family_members     state_pop
count       5.000000        5.000000  5.000000e+00
mean    24510.200000     5089.600000  1.102383e+07
std     47290.451681     8916.729154  1.606574e+07
min      1434.000000      432.000000  7.351390e+05
25%      2280.000000      582.000000  3.009733e+06
50%      2570.000000      864.000000  4.887681e+06
75%      7259.000000     2606.000000  7.025024e+06
max    109008.000000    20964.000000  3.946159e+07
Index(['region', 'state', 'individuals', 'family_members', 'state_pop'], dtype='object')
RangeIndex(start=0, stop=5, step=1)
[['East South Central' 'Alabama' 2570 864 4887681]
 ['Pacific' 'Alaska' 1434 582 735139]
 ['Mountain' 'Arizona' 7259 2606 7025024]
 ['West South Central' 'Arkansas' 2280 432 3009733]
 ['Pacific' 'California' 109008 20964 39461588]]
               region       state  individuals  family_members  state_pop
0  East South Central     Alabama         2570             864    4887681
2            Mountain     Arizona         7259            2606    7025024
1             Pacific      Alaska         1434             582     735139
4             Pacific  California       109008           20964   39461588
3  West South Central    Arkansas         2280             432    3009733
               region       state  individuals  family_members  state_pop
4             Pacific  California       109008           20964   39461588
2            Mountain     Arizona         7259            2606    7025024
0  East South Central     Alabama         2570             864    4887681
3  West South Central    Arkansas         2280             432    3009733
1             Pacific      Alaska         1434             582     735139
        state  individuals
0     Alabama         2570
1      Alaska         1434
2     Arizona         7259
3    Arkansas         2280
4  California       109008
               region    state  individuals  family_members  state_pop
0  East South Central  Alabama         2570             864    4887681
1             Pacific   Alaska         1434             582     735139
2            Mountain  Arizona         7259            2606    7025024
               region    state  individuals  family_members  state_pop
0  East South Central  Alabama         2570             864    4887681
1             Pacific   Alaska         1434             582     735139
2            Mountain  Arizona         7259            2606    7025024
               region    state  individuals  family_members  state_pop
0  East South Central  Alabama         2570             864    4887681
2            Mountain  Arizona         7259            2606    7025024
       individuals  state_pop
pct30       2338.0  3385322.6
pct40       2454.0  4136501.8
138982.86000000002
type  is_holiday
A     False         138982.86
Name: weekly_sales, dtype: float64
     unemployment                       fuel_price_usd_per_l                 \
              min    max    mean median                  min    max    mean
type
A           7.808  8.106  7.9272  7.808                0.679  0.749  0.7108


     median
type
A     0.715
              min          max         mean       median
     weekly_sales weekly_sales weekly_sales weekly_sales
type
A        17413.94     57258.43    27796.572      21827.9
All      17413.94     57258.43    27796.572      21827.9
                 type  department  weekly_sales  is_holiday  temperature_c  \
store date
1     2010-02-05    A           1      24924.50       False          5.728
      2010-03-05    A           2      21827.90       False          8.056
2     2010-04-02    A           1      57258.43       False         16.817
      2010-05-07    A           2      17413.94       False         22.528
      2010-06-04    A           2      17558.09       False         27.050

                  fuel_price_usd_per_l  unemployment
store date
1     2010-02-05                 0.679         8.106
      2010-03-05                 0.693         8.106
2     2010-04-02                 0.718         7.808
      2010-05-07                 0.749         7.808
      2010-06-04                 0.715         7.808
                 type  department  weekly_sales  is_holiday  temperature_c  \
store date
2     2010-06-04    A           2      17558.09       False         27.050
      2010-05-07    A           2      17413.94       False         22.528
      2010-04-02    A           1      57258.43       False         16.817
1     2010-03-05    A           2      21827.90       False          8.056
      2010-02-05    A           1      24924.50       False          5.728

                  fuel_price_usd_per_l  unemployment
store date
2     2010-06-04                 0.715         7.808
      2010-05-07                 0.749         7.808
      2010-04-02                 0.718         7.808
1     2010-03-05                 0.693         8.106
      2010-02-05                 0.679         8.106
                 type  department  weekly_sales  is_holiday  temperature_c  \
store date
1     2010-02-05    A           1      24924.50       False          5.728
      2010-03-05    A           2      21827.90       False          8.056
2     2010-04-02    A           1      57258.43       False         16.817

                  fuel_price_usd_per_l  unemployment
store date
1     2010-02-05                 0.679         8.106
      2010-03-05                 0.693         8.106
2     2010-04-02                 0.718         7.808
                  weekly_sales
store date
1     2010-03-05      21827.90
2     2010-04-02      57258.43
      2010-05-07      17413.94
      2010-06-04      17558.09
0   2010-02-05
1   2010-03-05
2   2010-04-02
3   2010-05-07
Name: date, dtype: datetime64[ns]
            store type  department  weekly_sales  is_holiday  temperature_c  \
date
2010-02-05      1    A           1      24924.50       False          5.728
2010-03-05      1    A           2      21827.90       False          8.056
2010-04-02      2    A           1      57258.43       False         16.817
2010-05-07      2    A           2      17413.94       False         22.528

            fuel_price_usd_per_l  unemployment
date
2010-02-05                 0.679         8.106
2010-03-05                 0.693         8.106
2010-04-02                 0.718         7.808
2010-05-07                 0.749         7.808
5
0    2010
1    2010
2    2010
3    2010
4    2010
Name: date, dtype: int64